# Generated by Django 4.1.2 on 2022-11-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_title_promotion_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='featured_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.product'),
        ),
    ]
