# Generated by Django 4.1.2 on 2022-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_promotion_featured_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
