# Generated by Django 4.1.2 on 2022-11-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_date_of_birth_customer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='memebership',
            new_name='membership',
        ),
    ]
