# Generated by Django 4.1.2 on 2022-11-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_placed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
